const router = require('express').Router();
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const verifyToken = require('../middleware/auth');
const pool = require('../db/pool');
const { generateSessionPDF } = require('../services/pdfService');
const auditLog = require('../middleware/audit');
const {
  getPatientProfile,
  upsertPatientProfile,
  getPatientSessions,
  getSessionById,
  updateSelectedDisease,
} = require('../models/patientQueries');

// GET /api/patient/profile
router.get('/profile', verifyToken, async (req, res) => {
  try {
    const profile = await getPatientProfile(req.user.userId);
    res.json({ profile: profile || null });
  } catch (err) {
    console.error('Get profile error:', err);
    res.status(500).json({ error: 'Failed to fetch profile' });
  }
});

// PUT /api/patient/profile
router.put('/profile', verifyToken, async (req, res) => {
  const {
    age, gender, weightKg, heightCm, bloodGroup,
    existingConditions, allergies, currentMedications,
    smokingStatus, alcoholUse,
  } = req.body;

  if (!age || !gender) {
    return res.status(400).json({ error: 'Age and gender are required' });
  }

  try {
    const profile = await upsertPatientProfile(req.user.userId, {
      age: parseInt(age),
      gender,
      weightKg: weightKg ? parseFloat(weightKg) : null,
      heightCm: heightCm ? parseFloat(heightCm) : null,
      bloodGroup: bloodGroup || null,
      existingConditions: existingConditions || [],
      allergies: allergies || [],
      currentMedications: currentMedications || [],
      smokingStatus: smokingStatus || null,
      alcoholUse: alcoholUse || null,
    });
    res.json({ profile });
  } catch (err) {
    console.error('Upsert profile error:', err);
    res.status(500).json({ error: 'Failed to save profile' });
  }
});

// GET /api/patient/prescriptions — list prescriptions written for this patient
router.get('/prescriptions', verifyToken, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT p.*, u.full_name AS doctor_name, u.email AS doctor_email
       FROM prescriptions p
       JOIN users u ON u.id = p.doctor_id
       WHERE p.patient_id = $1
       ORDER BY p.issued_at DESC
       LIMIT 50`,
      [req.user.userId]
    );
    res.json({ prescriptions: rows });
  } catch (err) {
    console.error('Get patient prescriptions error:', err);
    res.status(500).json({ error: 'Failed to fetch prescriptions' });
  }
});

// GET /api/patient/prescriptions/:id/pdf — download prescription PDF
router.get('/prescriptions/:id/pdf', verifyToken, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT p.*, u.full_name AS doctor_name
       FROM prescriptions p
       JOIN users u ON u.id = p.doctor_id
       WHERE p.id = $1 AND p.patient_id = $2`,
      [req.params.id, req.user.userId]
    );
    if (!rows.length) {
      return res.status(404).json({ error: 'Prescription not found' });
    }
    const rx = rows[0];
    const meds = typeof rx.medications === 'string' ? JSON.parse(rx.medications) : rx.medications;

    const PDFDocument = require('pdfkit');
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="prescription-${rx.id}.pdf"`);
    doc.pipe(res);

    // Header
    doc.fontSize(20).fillColor('#0d9488').text('MedAssist AI', { align: 'center' });
    doc.fontSize(12).fillColor('#666').text('Digital Prescription', { align: 'center' });
    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#e2e8f0').stroke();
    doc.moveDown();

    // Doctor & date
    doc.fontSize(11).fillColor('#334155');
    doc.text(`Prescribing Doctor: Dr. ${rx.doctor_name}`);
    doc.text(`Date: ${new Date(rx.issued_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
    doc.moveDown();

    // Medications table
    doc.fontSize(13).fillColor('#0d9488').text('Medications');
    doc.moveDown(0.5);
    (meds || []).forEach((m, i) => {
      doc.fontSize(11).fillColor('#1e293b').text(`${i + 1}. ${m.drug_name || '--'}`, { continued: false });
      doc.fontSize(10).fillColor('#64748b');
      if (m.dosage) doc.text(`   Dosage: ${m.dosage}`);
      if (m.frequency) doc.text(`   Frequency: ${m.frequency}`);
      if (m.duration) doc.text(`   Duration: ${m.duration}`);
      doc.moveDown(0.5);
    });

    // Notes
    if (rx.notes) {
      doc.moveDown();
      doc.fontSize(11).fillColor('#0d9488').text('Clinical Notes');
      doc.fontSize(10).fillColor('#334155').text(rx.notes);
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#94a3b8').text(
      'This prescription was generated by MedAssist AI. This is an educational CS 595 project and is NOT a substitute for professional medical advice.',
      { align: 'center' }
    );

    doc.end();
  } catch (err) {
    console.error('Patient prescription PDF error:', err);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

// GET /api/patient/sessions — list recent sessions with status + report linkage
router.get('/sessions', verifyToken, async (req, res) => {
  try {
    const sessions = await getPatientSessions(req.user.userId);
    res.json({ sessions });
  } catch (err) {
    console.error('Get sessions error:', err);
    res.status(500).json({ error: 'Failed to fetch sessions' });
  }
});

// GET /api/patient/sessions/:id — get a single session (ownership checked)
router.get('/sessions/:id', verifyToken, async (req, res) => {
  try {
    const session = await getSessionById(req.params.id, req.user.userId);
    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }
    res.json({ session });
  } catch (err) {
    console.error('Get session by id error:', err);
    res.status(500).json({ error: 'Failed to fetch session' });
  }
});

// PUT /api/patient/sessions/:id/disease — save selected disease + advance status
router.put('/sessions/:id/disease', verifyToken, async (req, res) => {
  const { disease } = req.body;
  if (!disease || !disease.disease) {
    return res.status(400).json({ error: 'disease object with disease name is required' });
  }

  try {
    // Verify session belongs to this patient before writing
    const existing = await getSessionById(req.params.id, req.user.userId);
    if (!existing) {
      return res.status(404).json({ error: 'Session not found' });
    }

    await updateSelectedDisease(req.params.id, disease);
    res.json({ ok: true });
  } catch (err) {
    console.error('Update selected disease error:', err);
    res.status(500).json({ error: 'Failed to save selected disease' });
  }
});

// GET /api/patient/sessions/:id/export-pdf — generate PDF for a complete session
router.get('/sessions/:id/export-pdf', verifyToken, auditLog('export_pdf', 'session'), async (req, res) => {
  try {
    const session = await getSessionById(req.params.id, req.user.userId);
    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    // Fetch linked blood report if any
    let analysis = {};
    let tabletRecommendations = [];
    let riskScores = null;
    let followUp = null;

    if (session.report_id) {
      const { rows } = await pool.query(
        'SELECT analysis, tablet_recommendations, risk_scores, follow_up FROM blood_reports WHERE id = $1',
        [session.report_id]
      );
      if (rows.length) {
        analysis = rows[0].analysis || {};
        tabletRecommendations = rows[0].tablet_recommendations || [];
        riskScores = rows[0].risk_scores || null;
        followUp = rows[0].follow_up || null;
      }
    }

    // Fetch patient name
    const { rows: userRows } = await pool.query('SELECT full_name FROM users WHERE id = $1', [req.user.userId]);

    const pdfBuffer = await generateSessionPDF({
      patientName: userRows[0]?.full_name || 'Patient',
      disease: session.selected_disease || 'N/A',
      symptoms: session.symptoms || [],
      analysis,
      tabletRecommendations,
      riskScores,
      followUp,
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=MedAssist_Report_${req.params.id}.pdf`);
    res.send(pdfBuffer);
  } catch (err) {
    console.error('Export PDF error:', err);
    res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

// POST /api/patient/sessions/:id/share — generate a share token for a session
router.post('/sessions/:id/share', verifyToken, auditLog('share_report', 'session'), async (req, res) => {
  try {
    const session = await getSessionById(req.params.id, req.user.userId);
    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    const shareToken = crypto.randomBytes(24).toString('hex');
    const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); // 7 days

    await pool.query(
      `INSERT INTO report_shares (token, session_id, patient_id, expires_at)
       VALUES ($1, $2, $3, $4)`,
      [shareToken, req.params.id, req.user.userId, expiresAt]
    );

    const clientUrl = process.env.CLIENT_URL || 'http://localhost:5173';
    res.json({
      token: shareToken,
      url: `${clientUrl}/shared/${shareToken}`,
      expiresAt,
    });
  } catch (err) {
    console.error('Share session error:', err);
    res.status(500).json({ error: 'Failed to share session' });
  }
});

// GET /api/patient/vitals — get patient's vitals (query: type, days)
router.get('/vitals', verifyToken, async (req, res) => {
  try {
    const { type, days } = req.query;
    let query = 'SELECT * FROM vitals_logs WHERE patient_id = $1';
    const params = [req.user.userId];

    if (type) {
      params.push(type);
      query += ` AND type = $${params.length}`;
    }
    if (days) {
      params.push(parseInt(days));
      query += ` AND recorded_at >= NOW() - INTERVAL '1 day' * $${params.length}`;
    }

    query += ' ORDER BY recorded_at DESC LIMIT 200';
    const { rows } = await pool.query(query, params);
    res.json({ vitals: rows });
  } catch (err) {
    console.error('Get vitals error:', err);
    res.status(500).json({ error: 'Failed to fetch vitals' });
  }
});

// POST /api/patient/vitals — save a new vital reading
router.post('/vitals', verifyToken, async (req, res) => {
  const { type, value, value2, unit } = req.body;
  if (!type || value === undefined) {
    return res.status(400).json({ error: 'type and value are required' });
  }

  try {
    const { rows } = await pool.query(
      `INSERT INTO vitals_logs (patient_id, type, value, value2, unit)
       VALUES ($1, $2, $3, $4, $5)
       RETURNING *`,
      [req.user.userId, type, value, value2 || null, unit || null]
    );
    res.status(201).json({ vital: rows[0] });
  } catch (err) {
    console.error('Save vital error:', err);
    res.status(500).json({ error: 'Failed to save vital' });
  }
});

// GET /api/patient/medications — get patient's active medications
router.get('/medications', verifyToken, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT * FROM medication_logs
       WHERE patient_id = $1
       ORDER BY taken_at DESC LIMIT 100`,
      [req.user.userId]
    );
    res.json({ medications: rows });
  } catch (err) {
    console.error('Get medications error:', err);
    res.status(500).json({ error: 'Failed to fetch medications' });
  }
});

// POST /api/patient/medications — log a medication dose
router.post('/medications', verifyToken, async (req, res) => {
  const { medication_name, dose, report_id } = req.body;
  if (!medication_name) {
    return res.status(400).json({ error: 'medication_name is required' });
  }

  try {
    const { rows } = await pool.query(
      `INSERT INTO medication_logs (patient_id, medication_name, dose, report_id, active)
       VALUES ($1, $2, $3, $4, true)
       RETURNING *`,
      [req.user.userId, medication_name, dose || null, report_id || null]
    );
    res.status(201).json({ medication: rows[0] });
  } catch (err) {
    console.error('Log medication error:', err);
    res.status(500).json({ error: 'Failed to log medication' });
  }
});

// PUT /api/patient/medications/:id/toggle — toggle medication active status
router.put('/medications/:id/toggle', verifyToken, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `UPDATE medication_logs SET active = NOT active
       WHERE id = $1 AND patient_id = $2
       RETURNING *`,
      [req.params.id, req.user.userId]
    );
    if (!rows.length) {
      return res.status(404).json({ error: 'Medication not found' });
    }
    res.json({ medication: rows[0] });
  } catch (err) {
    console.error('Toggle medication error:', err);
    res.status(500).json({ error: 'Failed to toggle medication' });
  }
});

// GET /api/patient/medical-id — get patient's medical ID
router.get('/medical-id', verifyToken, async (req, res) => {
  try {
    const { rows } = await pool.query(
      'SELECT id, patient_id, emergency_name, emergency_phone, blood_type, organ_donor, critical_notes FROM medical_id WHERE patient_id = $1',
      [req.user.userId]
    );
    res.json({ medicalId: rows[0] || null });
  } catch (err) {
    console.error('Get medical ID error:', err);
    res.status(500).json({ error: 'Failed to fetch medical ID' });
  }
});

// PUT /api/patient/medical-id — save/update medical ID
router.put('/medical-id', verifyToken, async (req, res) => {
  const { emergency_name, emergency_phone, blood_type, organ_donor, critical_notes, pin } = req.body;

  try {
    let pinHash = null;
    if (pin) {
      pinHash = await bcrypt.hash(String(pin), 10);
    }

    // Check if record exists
    const { rows: existing } = await pool.query(
      'SELECT id FROM medical_id WHERE patient_id = $1',
      [req.user.userId]
    );

    let result;
    if (existing.length > 0) {
      const updateFields = [
        'emergency_name = $2', 'emergency_phone = $3', 'blood_type = $4',
        'organ_donor = $5', 'critical_notes = $6',
      ];
      const params = [req.user.userId, emergency_name || null, emergency_phone || null,
        blood_type || null, organ_donor || false, critical_notes || null];

      if (pinHash) {
        params.push(pinHash);
        updateFields.push(`pin_hash = $${params.length}`);
      }

      result = await pool.query(
        `UPDATE medical_id SET ${updateFields.join(', ')} WHERE patient_id = $1 RETURNING id, patient_id, emergency_name, emergency_phone, blood_type, organ_donor, critical_notes`,
        params
      );
    } else {
      result = await pool.query(
        `INSERT INTO medical_id (patient_id, emergency_name, emergency_phone, blood_type, organ_donor, critical_notes, pin_hash)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         RETURNING id, patient_id, emergency_name, emergency_phone, blood_type, organ_donor, critical_notes`,
        [req.user.userId, emergency_name || null, emergency_phone || null,
         blood_type || null, organ_donor || false, critical_notes || null, pinHash]
      );
    }

    res.json({ medicalId: result.rows[0] });
  } catch (err) {
    console.error('Save medical ID error:', err);
    res.status(500).json({ error: 'Failed to save medical ID' });
  }
});

// GET /api/patient/health-timeline — aggregate session data into timeline events
router.get('/health-timeline', verifyToken, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT
         s.id AS session_id,
         s.selected_disease AS disease,
         s.status,
         s.created_at,
         'session' AS event_type,
         s.symptoms
       FROM symptom_sessions s
       WHERE s.patient_id = $1
       ORDER BY s.created_at DESC
       LIMIT 50`,
      [req.user.userId]
    );

    // Also get vitals as events
    const { rows: vitals } = await pool.query(
      `SELECT id, type, value, value2, unit, recorded_at AS created_at, 'vital' AS event_type
       FROM vitals_logs
       WHERE patient_id = $1
       ORDER BY recorded_at DESC
       LIMIT 50`,
      [req.user.userId]
    );

    // Merge and sort by date
    const timeline = [...rows, ...vitals].sort(
      (a, b) => new Date(b.created_at) - new Date(a.created_at)
    );

    res.json({ timeline });
  } catch (err) {
    console.error('Health timeline error:', err);
    res.status(500).json({ error: 'Failed to fetch timeline' });
  }
});

// GET /api/patient/symptoms/trends — compare symptom severity across sessions
router.get('/symptoms/trends', verifyToken, async (req, res) => {
  try {
    const { rows } = await pool.query(
      `SELECT id, symptoms, selected_disease, created_at
       FROM symptom_sessions
       WHERE patient_id = $1
       ORDER BY created_at DESC
       LIMIT 20`,
      [req.user.userId]
    );

    // Build trend data: extract symptom names and severities per session
    const trends = rows.map((s) => {
      const symptoms = Array.isArray(s.symptoms) ? s.symptoms : [];
      return {
        sessionId: s.id,
        disease: s.selected_disease,
        date: s.created_at,
        symptoms: symptoms.map((sym) => ({
          name: typeof sym === 'string' ? sym : sym.symptom || sym.name || 'unknown',
          severity: sym.severity || null,
          duration: sym.duration || null,
        })),
      };
    });

    res.json({ trends });
  } catch (err) {
    console.error('Symptom trends error:', err);
    res.status(500).json({ error: 'Failed to fetch symptom trends' });
  }
});

// POST /api/patient/sessions/:id/second-opinion — re-run diagnostic agent on same session
router.post('/sessions/:id/second-opinion', verifyToken, async (req, res) => {
  try {
    const session = await getSessionById(req.params.id, req.user.userId);
    if (!session) {
      return res.status(404).json({ error: 'Session not found' });
    }

    // Re-run the diagnostic agent with the same symptoms
    const { runDiagnosticAgent } = require('../agents/diagnosticAgent');
    const patientProfile = await getPatientProfile(req.user.userId);

    const result = await runDiagnosticAgent({
      sessionId: req.params.id,
      symptoms: session.symptoms,
      patientProfile,
    });

    res.json({
      sessionId: req.params.id,
      diseases: result.diseases,
      steps: result.steps?.length || 0,
      turns: result.turns,
      isSecondOpinion: true,
    });
  } catch (err) {
    console.error('Second opinion error:', err);
    res.status(500).json({ error: 'Failed to get second opinion' });
  }
});

module.exports = router;
