import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import toast from 'react-hot-toast';
import api from '../../services/api';

const fadeIn = { hidden: { opacity: 0, y: 16 }, visible: { opacity: 1, y: 0, transition: { duration: 0.4 } } };
const cardAnim = { hidden: { opacity: 0, y: 12 }, visible: (i) => ({ opacity: 1, y: 0, transition: { delay: i * 0.05, duration: 0.3 } }) };

const STATUS_STYLE = {
  normal:        'bg-green-50 text-green-700',
  low:           'bg-yellow-50 text-yellow-800',
  high:          'bg-orange-50 text-orange-800',
  critical_low:  'bg-red-100 text-red-800',
  critical_high: 'bg-red-200 text-red-900',
};

export default function SharedReports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState(null);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const { data } = await api.get('/doctor-assist/shared-reports');
        setReports(data.reports || []);
      } catch {
        toast.error('Failed to load shared reports');
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  const formatDate = (d) =>
    new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="w-10 h-10 border-4 border-teal-500 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  // Detail View
  if (selectedReport) {
    const r = selectedReport;
    const analysis = r.analysis || {};
    return (
      <motion.div variants={fadeIn} initial="hidden" animate="visible" className="max-w-3xl mx-auto space-y-6">
        <button
          onClick={() => setSelectedReport(null)}
          className="flex items-center gap-2 text-sm text-teal-600 hover:text-teal-700 font-medium"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to Reports
        </button>

        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
          <div className="flex items-start justify-between gap-4 mb-4">
            <div>
              <h1 className="text-xl font-bold text-slate-800">
                {r.patient_name || 'Patient'} - Report
              </h1>
              <p className="text-sm text-slate-500 mt-0.5">
                {r.disease || 'Unknown condition'} | Shared {formatDate(r.shared_at)}
              </p>
            </div>
            <span className="px-3 py-1 bg-teal-50 text-teal-700 text-xs font-semibold rounded-full">Read Only</span>
          </div>

          <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-xs text-amber-700 mb-4">
            This is a patient-shared report. The information here is generated by AI and should be verified clinically.
          </div>
        </div>

        {/* Summary */}
        {analysis.summary && (
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
            <h2 className="text-lg font-bold text-slate-800 border-b border-slate-100 pb-2 mb-4">Summary</h2>
            <p className="text-slate-700 leading-relaxed">{analysis.summary.overall_assessment}</p>
            {analysis.summary.root_cause && (
              <p className="text-sm text-slate-500 mt-2">
                <span className="font-medium text-slate-700">Root cause:</span> {analysis.summary.root_cause}
              </p>
            )}
          </div>
        )}

        {/* Findings */}
        {analysis.abnormal_findings?.length > 0 && (
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
            <h2 className="text-lg font-bold text-slate-800 border-b border-slate-100 pb-2 mb-4">Findings</h2>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-xs text-slate-400 border-b border-slate-100">
                    <th className="pb-2 font-medium">Parameter</th>
                    <th className="pb-2 font-medium">Value</th>
                    <th className="pb-2 font-medium">Range</th>
                    <th className="pb-2 font-medium">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {analysis.abnormal_findings.map((f, i) => (
                    <tr key={i}>
                      <td className="py-2 pr-3 font-medium text-slate-800">{f.parameter}</td>
                      <td className="py-2 pr-3 font-mono font-semibold">{f.your_value}</td>
                      <td className="py-2 pr-3 text-slate-500 font-mono text-xs">{f.normal_range}</td>
                      <td className="py-2">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-semibold ${STATUS_STYLE[f.status] || 'bg-slate-100 text-slate-600'}`}>
                          {f.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Tablets */}
        {r.tabletRecommendations?.length > 0 && (
          <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6">
            <h2 className="text-lg font-bold text-slate-800 border-b border-slate-100 pb-2 mb-4">Tablet Recommendations</h2>
            <div className="space-y-3">
              {r.tabletRecommendations.map((med, i) => (
                <div key={i} className="border border-slate-100 rounded-xl p-4 bg-slate-50">
                  <h3 className="font-bold text-slate-800">{med.name}</h3>
                  <div className="grid grid-cols-3 gap-2 text-sm mt-2">
                    <div><span className="text-xs text-slate-400">Dosage:</span> <span className="text-slate-700">{med.dosage || '--'}</span></div>
                    <div><span className="text-xs text-slate-400">Frequency:</span> <span className="text-slate-700">{med.frequency || '--'}</span></div>
                    <div><span className="text-xs text-slate-400">Duration:</span> <span className="text-slate-700">{med.duration || '--'}</span></div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </motion.div>
    );
  }

  // List View
  return (
    <motion.div variants={fadeIn} initial="hidden" animate="visible" className="max-w-4xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-800">Shared Reports</h1>
        <p className="text-sm text-slate-500 mt-1">Reports shared with you by patients</p>
      </div>

      {reports.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-12 text-center">
          <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <p className="text-slate-500">No shared reports yet.</p>
          <p className="text-xs text-slate-400 mt-1">When patients share their reports with you, they will appear here.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reports.map((report, i) => (
            <motion.div
              key={report.id || i}
              custom={i}
              variants={cardAnim}
              initial="hidden"
              animate="visible"
              onClick={() => setSelectedReport(report)}
              className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5 hover:border-teal-300 hover:shadow-md transition-all cursor-pointer"
            >
              <div className="flex items-start justify-between gap-3 mb-3">
                <div className="flex-1 min-w-0">
                  <h3 className="font-bold text-slate-800 truncate">{report.patient_name || 'Patient'}</h3>
                  <p className="text-sm text-teal-600 font-medium mt-0.5">{report.disease || 'General Report'}</p>
                </div>
                <span className="text-xs text-slate-400 shrink-0">{formatDate(report.shared_at)}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-500">
                  {report.findings_count || 0} findings
                </span>
                <span className="text-xs text-teal-600 font-medium">View Details &rarr;</span>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </motion.div>
  );
}
